### ISSUE TITLE
8-1202

### ISSUE THREAD

**Issue by libinggit** [Mangosir/Error#2]
厨房：1、拉门关不严实 2、拉门上面木板坏掉 3、窗台诡辩及角需要打胶
大门：1、大门内开 2、大门内侧漆破坏 3、门套划痕
客厅：1、地板松动（与阳台连接处、厨房门口） 2、电视柜对面墙面不平整
储衣间：1、房间角需打蜡 2、门需要重新贴角
主卧：1、门口地板松动 2、窗户与墙面缝隙大 3、门锁坏掉 4、阳台墙纸起皮
次卧：1、门口地板松动 2、窗户转角空隙大 3、墙转角有裂缝
卫生间：1、洗手台大理石需打磨 2、洗水台下面台灯松动 3、淋浴门需改成外开 4、下水道不漏水 5、开关缝隙大
阳台：1、地砖勾缝 2、阳台防护墙与玻璃之间有大缝隙
储物间：门前地板松动

**Comment by Mangosir** [comment]
已处理
